//! Cluster Coordinator for Multi-Node GPU Communication
//! 
//! Coordinates distributed workloads across a 4-node, 16-GPU cluster:
//! - Node discovery and rank assignment
//! - Inter-node communication via TCP/Sockets
//! - Workload distribution across nodes
//! - Fault detection and recovery
//! 
//! Network Configuration:
//! - Uses TCP/IP (Ethernet) for inter-node communication
//! - NCCL handles GPU-to-GPU collective operations
//! - This coordinator handles node-level orchestration

const std = @import("std");
const builtin = @import("builtin");
const net = std.net;
const posix = std.posix;

const log = std.log.scoped(.cluster_coordinator);

// Import GPU modules
const multi_gpu = @import("../gpu/multi_gpu_manager.zig");
const nccl = @import("../gpu/nccl_bindings.zig");

// ============================================================================
// Cluster Configuration
// ============================================================================

pub const ClusterTopology = struct {
    /// Maximum nodes in cluster
    pub const MAX_NODES: u8 = 4;
    /// Maximum GPUs per node
    pub const MAX_GPUS_PER_NODE: u8 = 4;
    /// Maximum total GPUs
    pub const MAX_TOTAL_GPUS: u8 = MAX_NODES * MAX_GPUS_PER_NODE; // 16
    
    /// Default coordinator port
    pub const DEFAULT_COORDINATOR_PORT: u16 = 29500;
    /// NCCL communication port range start
    pub const NCCL_PORT_START: u16 = 29400;
};

// ============================================================================
// Node Information
// ============================================================================

pub const NodeStatus = enum(u8) {
    unknown = 0,
    initializing = 1,
    ready = 2,
    busy = 3,
    error_state = 4,
    offline = 5,
};

pub const NodeInfo = struct {
    /// Node ID (0-3)
    node_id: u8,
    /// Hostname or IP address
    hostname: [256]u8 = [_]u8{0} ** 256,
    hostname_len: usize = 0,
    /// Number of GPUs on this node
    gpu_count: u8 = 0,
    /// GPU architectures on this node
    gpu_architectures: [ClusterTopology.MAX_GPUS_PER_NODE]multi_gpu.GpuArchitecture = 
        [_]multi_gpu.GpuArchitecture{.unknown} ** ClusterTopology.MAX_GPUS_PER_NODE,
    /// Total GPU memory on this node (bytes)
    total_gpu_memory: u64 = 0,
    /// Free GPU memory on this node (bytes)
    free_gpu_memory: u64 = 0,
    /// Current status
    status: NodeStatus = .unknown,
    /// Last heartbeat timestamp
    last_heartbeat: i64 = 0,
    
    pub fn getHostname(self: *const NodeInfo) []const u8 {
        return self.hostname[0..self.hostname_len];
    }
    
    pub fn setHostname(self: *NodeInfo, name: []const u8) void {
        const len = @min(name.len, self.hostname.len);
        @memcpy(self.hostname[0..len], name[0..len]);
        self.hostname_len = len;
    }
    
    pub fn getTotalMemoryGB(self: *const NodeInfo) f32 {
        return @as(f32, @floatFromInt(self.total_gpu_memory)) / (1024 * 1024 * 1024);
    }
};

// ============================================================================
// Cluster Coordinator
// ============================================================================

pub const ClusterCoordinator = struct {
    allocator: std.mem.Allocator,
    
    // Cluster identity
    /// Total number of nodes in cluster
    world_size: u8 = 1,
    /// This node's ID (0 to MAX_NODES-1)
    node_id: u8 = 0,
    /// Is this node the coordinator (rank 0)?
    is_coordinator: bool = false,
    
    // Local GPU info
    /// Number of GPUs on this node
    local_gpu_count: u8 = 0,
    /// Local GPU manager
    gpu_manager: ?*multi_gpu.MultiGpuManager = null,
    
    // Cluster state
    /// Information about all nodes
    nodes: [ClusterTopology.MAX_NODES]?NodeInfo = [_]?NodeInfo{null} ** ClusterTopology.MAX_NODES,
    /// Total GPUs in cluster
    total_gpus: u8 = 0,
    
    // Network
    /// Coordinator hostname/IP
    coordinator_host: [256]u8 = [_]u8{0} ** 256,
    coordinator_host_len: usize = 0,
    /// Coordinator port
    coordinator_port: u16 = ClusterTopology.DEFAULT_COORDINATOR_PORT,
    
    // NCCL
    /// NCCL unique ID (generated by coordinator, shared with all)
    nccl_unique_id: nccl.NcclUniqueId = .{},
    /// NCCL communicator
    nccl_comm: ?*nccl.NcclCommunicator = null,
    
    // State
    initialized: bool = false,
    
    const Self = @This();
    
    /// Initialize cluster coordinator from environment variables
    pub fn init(allocator: std.mem.Allocator) !*Self {
        var self = try allocator.create(Self);
        self.* = .{
            .allocator = allocator,
        };
        
        // Read configuration from environment
        self.readEnvironment();
        
        // Initialize local GPU manager
        self.gpu_manager = multi_gpu.MultiGpuManager.init(allocator) catch |err| blk: {
            log.warn("Failed to initialize GPU manager: {}", .{err});
            break :blk null;
        };
        
        if (self.gpu_manager) |mgr| {
            self.local_gpu_count = mgr.local_gpu_count;
        }
        
        // Set up this node's info
        try self.setupLocalNode();
        
        self.initialized = true;
        
        log.info("Cluster coordinator initialized: node {}/{}, {} local GPUs", .{
            self.node_id,
            self.world_size,
            self.local_gpu_count,
        });
        
        return self;
    }
    
    pub fn deinit(self: *Self) void {
        if (self.nccl_comm) |comm| {
            comm.deinit();
        }
        if (self.gpu_manager) |mgr| {
            mgr.deinit();
        }
        self.allocator.destroy(self);
    }
    
    /// Read cluster configuration from environment variables
    fn readEnvironment(self: *Self) void {
        // Standard distributed training environment variables
        if (std.posix.getenv("WORLD_SIZE")) |ws| {
            // WORLD_SIZE typically refers to total ranks (GPUs), not nodes
            const total_gpus = std.fmt.parseInt(u8, ws, 10) catch 1;
            // Assume 4 GPUs per node
            self.world_size = @max(1, total_gpus / ClusterTopology.MAX_GPUS_PER_NODE);
        }
        
        if (std.posix.getenv("NODE_RANK")) |nr| {
            self.node_id = std.fmt.parseInt(u8, nr, 10) catch 0;
        } else if (std.posix.getenv("GROUP_RANK")) |gr| {
            self.node_id = std.fmt.parseInt(u8, gr, 10) catch 0;
        }
        
        if (std.posix.getenv("LOCAL_WORLD_SIZE")) |lws| {
            self.local_gpu_count = std.fmt.parseInt(u8, lws, 10) catch 1;
        }
        
        // Coordinator info
        if (std.posix.getenv("MASTER_ADDR")) |addr| {
            const len = @min(addr.len, self.coordinator_host.len);
            @memcpy(self.coordinator_host[0..len], addr[0..len]);
            self.coordinator_host_len = len;
        }
        
        if (std.posix.getenv("MASTER_PORT")) |port| {
            self.coordinator_port = std.fmt.parseInt(u16, port, 10) catch ClusterTopology.DEFAULT_COORDINATOR_PORT;
        }
        
        // Determine if this is the coordinator
        self.is_coordinator = (self.node_id == 0);
    }
    
    /// Set up local node information
    fn setupLocalNode(self: *Self) !void {
        var node_info = NodeInfo{
            .node_id = self.node_id,
            .gpu_count = self.local_gpu_count,
            .status = .ready,
            .last_heartbeat = std.time.timestamp(),
        };
        
        // Get hostname
        var hostname_buf: [256]u8 = undefined;
        const hostname = self.getHostname(&hostname_buf) catch "localhost";
        node_info.setHostname(hostname);
        
        // Get GPU info from manager
        if (self.gpu_manager) |mgr| {
            node_info.total_gpu_memory = mgr.getTotalMemory();
            node_info.free_gpu_memory = mgr.getTotalFreeMemory();
            
            for (0..mgr.local_gpu_count) |i| {
                if (mgr.local_devices[i]) |device| {
                    node_info.gpu_architectures[i] = device.architecture;
                }
            }
        }
        
        self.nodes[self.node_id] = node_info;
        self.total_gpus = self.local_gpu_count;
    }
    
    /// Get local hostname
    fn getHostname(self: *Self, buf: []u8) ![]const u8 {
        _ = self;
        
        // Try to get hostname from system
        if (std.posix.getenv("HOSTNAME")) |h| {
            return h;
        }
        
        // Use gethostname syscall
        var hostname: [256]u8 = undefined;
        const result = std.c.gethostname(&hostname, hostname.len);
        if (result == 0) {
            const len = std.mem.indexOfScalar(u8, &hostname, 0) orelse hostname.len;
            @memcpy(buf[0..len], hostname[0..len]);
            return buf[0..len];
        }
        
        return "localhost";
    }
    
    /// Initialize NCCL communication across all nodes
    pub fn initNccl(self: *Self) !void {
        if (self.is_coordinator) {
            // Coordinator generates the unique ID
            self.nccl_unique_id = try nccl.generateUniqueId();
            log.info("Generated NCCL unique ID", .{});
            
            // In production: broadcast unique ID to all nodes via TCP
            // For now, assume it's distributed via shared filesystem or rendezvous
        } else {
            // Non-coordinator nodes receive the unique ID
            // In production: receive from coordinator via TCP
            log.info("Waiting for NCCL unique ID from coordinator", .{});
        }
        
        // Initialize NCCL communicator
        const config = nccl.NcclConfig{
            .world_size = self.total_gpus,
            .local_world_size = self.local_gpu_count,
            .node_id = self.node_id,
            .rank = self.node_id * ClusterTopology.MAX_GPUS_PER_NODE,
            .local_rank = 0,
        };
        
        self.nccl_comm = try nccl.NcclCommunicator.initMultiNode(
            self.allocator,
            config,
            self.nccl_unique_id,
        );
        
        log.info("NCCL initialized for node {}", .{self.node_id});
    }
    
    // ========================================================================
    // Cluster Operations
    // ========================================================================
    
    /// Barrier: Wait for all nodes to reach this point
    pub fn barrier(self: *Self) !void {
        if (!self.initialized) return error.NotInitialized;
        
        log.debug("Barrier: node {} waiting", .{self.node_id});
        
        // In production: use TCP or NCCL AllReduce for barrier
        // For now, just sync local GPUs
        if (self.nccl_comm) |comm| {
            try comm.synchronizeAll();
        }
        
        log.debug("Barrier: node {} passed", .{self.node_id});
    }
    
    /// Get global rank for a local GPU
    pub fn getGlobalRank(self: *Self, local_gpu: u8) u8 {
        return self.node_id * ClusterTopology.MAX_GPUS_PER_NODE + local_gpu;
    }
    
    /// Get node ID from global rank
    pub fn getNodeFromRank(self: *Self, global_rank: u8) u8 {
        _ = self;
        return global_rank / ClusterTopology.MAX_GPUS_PER_NODE;
    }
    
    /// Get local GPU ID from global rank
    pub fn getLocalGpuFromRank(self: *Self, global_rank: u8) u8 {
        _ = self;
        return global_rank % ClusterTopology.MAX_GPUS_PER_NODE;
    }
    
    /// Check if a global rank is on this node
    pub fn isLocalRank(self: *Self, global_rank: u8) bool {
        return self.getNodeFromRank(global_rank) == self.node_id;
    }
    
    /// Get total GPU count across cluster
    pub fn getTotalGpuCount(self: *Self) u8 {
        var total: u8 = 0;
        for (self.nodes) |maybe_node| {
            if (maybe_node) |node| {
                total += node.gpu_count;
            }
        }
        return total;
    }
    
    /// Get total GPU memory across cluster
    pub fn getTotalClusterMemory(self: *Self) u64 {
        var total: u64 = 0;
        for (self.nodes) |maybe_node| {
            if (maybe_node) |node| {
                total += node.total_gpu_memory;
            }
        }
        return total;
    }
    
    // ========================================================================
    // Workload Distribution
    // ========================================================================
    
    /// Distribute a batch across the entire cluster
    pub fn distributeClusterWorkload(
        self: *Self,
        total_batch_size: usize,
    ) ClusterWorkloadDistribution {
        var distribution = ClusterWorkloadDistribution{
            .total_batch_size = total_batch_size,
        };
        
        // Calculate total GPUs
        const total_gpus = self.getTotalGpuCount();
        if (total_gpus == 0) return distribution;
        
        // Split batch evenly across all GPUs
        const base_size = total_batch_size / total_gpus;
        const remainder = total_batch_size % total_gpus;
        
        var offset: usize = 0;
        var global_rank: u8 = 0;
        
        for (0..ClusterTopology.MAX_NODES) |node_idx| {
            if (self.nodes[node_idx]) |node| {
                for (0..node.gpu_count) |local_gpu| {
                    const extra: usize = if (global_rank < remainder) 1 else 0;
                    const chunk_size = base_size + extra;
                    
                    distribution.tasks[global_rank] = ClusterTask{
                        .global_rank = global_rank,
                        .node_id = @intCast(node_idx),
                        .local_gpu = @intCast(local_gpu),
                        .batch_start = offset,
                        .batch_size = chunk_size,
                    };
                    
                    offset += chunk_size;
                    global_rank += 1;
                    distribution.task_count += 1;
                }
            }
        }
        
        return distribution;
    }
    
    /// Get tasks for this node only
    pub fn getLocalTasks(self: *Self, distribution: *const ClusterWorkloadDistribution) []const ?ClusterTask {
        const start_rank = self.node_id * ClusterTopology.MAX_GPUS_PER_NODE;
        const end_rank = start_rank + self.local_gpu_count;
        return distribution.tasks[start_rank..end_rank];
    }
    
    // ========================================================================
    // Status and Monitoring
    // ========================================================================
    
    /// Update node heartbeat
    pub fn updateHeartbeat(self: *Self) void {
        if (self.nodes[self.node_id]) |*node| {
            node.last_heartbeat = std.time.timestamp();
        }
    }
    
    /// Check if a node is alive (heartbeat within last 30 seconds)
    pub fn isNodeAlive(self: *Self, node_id: u8) bool {
        if (self.nodes[node_id]) |node| {
            const now = std.time.timestamp();
            const heartbeat_timeout = 30; // seconds
            return (now - node.last_heartbeat) < heartbeat_timeout;
        }
        return false;
    }
    
    /// Print cluster status
    pub fn printStatus(self: *Self) void {
        log.info("=== Cluster Status ===", .{});
        log.info("Nodes: {}", .{self.world_size});
        log.info("Total GPUs: {}", .{self.getTotalGpuCount()});
        log.info("Total Memory: {d:.1f} GB", .{
            @as(f32, @floatFromInt(self.getTotalClusterMemory())) / (1024 * 1024 * 1024),
        });
        log.info("This Node: {} (coordinator: {})", .{ self.node_id, self.is_coordinator });
        
        for (0..ClusterTopology.MAX_NODES) |i| {
            if (self.nodes[i]) |node| {
                const alive = if (self.isNodeAlive(@intCast(i))) "✓" else "✗";
                log.info("  Node {}: {s} - {} GPUs, {d:.1f} GB, status: {} {s}", .{
                    i,
                    node.getHostname(),
                    node.gpu_count,
                    node.getTotalMemoryGB(),
                    node.status,
                    alive,
                });
            }
        }
    }
};

// ============================================================================
// Cluster Workload Distribution
// ============================================================================

pub const ClusterTask = struct {
    /// Global GPU rank (0-15)
    global_rank: u8,
    /// Node ID (0-3)
    node_id: u8,
    /// Local GPU ID within node (0-3)
    local_gpu: u8,
    /// Start index in batch
    batch_start: usize,
    /// Number of items for this GPU
    batch_size: usize,
    /// Completion status
    completed: bool = false,
};

pub const ClusterWorkloadDistribution = struct {
    tasks: [ClusterTopology.MAX_TOTAL_GPUS]?ClusterTask = 
        [_]?ClusterTask{null} ** ClusterTopology.MAX_TOTAL_GPUS,
    task_count: u8 = 0,
    total_batch_size: usize = 0,
    
    pub fn getTasks(self: *const ClusterWorkloadDistribution) []const ?ClusterTask {
        return self.tasks[0..self.task_count];
    }
    
    /// Get task for a specific global rank
    pub fn getTask(self: *const ClusterWorkloadDistribution, global_rank: u8) ?ClusterTask {
        if (global_rank >= ClusterTopology.MAX_TOTAL_GPUS) return null;
        return self.tasks[global_rank];
    }
};

// ============================================================================
// Ring AllReduce for Network-Efficient Gradient Sync
// ============================================================================

pub const RingAllReduce = struct {
    coordinator: *ClusterCoordinator,
    
    const Self = @This();
    
    pub fn init(coordinator: *ClusterCoordinator) Self {
        return .{ .coordinator = coordinator };
    }
    
    /// Perform ring AllReduce across cluster
    /// This is bandwidth-optimal for large tensors over network
    pub fn reduce(
        self: *Self,
        local_gpu: u8,
        data: []f32,
    ) !void {
        const total_gpus = self.coordinator.getTotalGpuCount();
        if (total_gpus <= 1) return; // Nothing to reduce
        
        // Ring AllReduce algorithm:
        // 1. Split data into `total_gpus` chunks
        // 2. Each GPU sends chunk[i] to GPU[(rank+1) % total] and receives into chunk[(rank-1) % total]
        // 3. Repeat `total_gpus - 1` times for reduce-scatter phase
        // 4. Repeat `total_gpus - 1` times for all-gather phase
        
        // For NCCL, this is handled internally with optimized implementation
        if (self.coordinator.nccl_comm) |comm| {
            const data_ptr: *anyopaque = @ptrCast(data.ptr);
            try comm.allReduce(
                local_gpu,
                data_ptr,
                data_ptr,
                data.len,
                .ncclFloat32,
                .ncclSum,
            );
        }
        
        log.debug("Ring AllReduce completed on GPU {} with {} elements", .{ local_gpu, data.len });
    }
};

// ============================================================================
// Tests
// ============================================================================

test "ClusterTopology constants" {
    try std.testing.expectEqual(@as(u8, 4), ClusterTopology.MAX_NODES);
    try std.testing.expectEqual(@as(u8, 4), ClusterTopology.MAX_GPUS_PER_NODE);
    try std.testing.expectEqual(@as(u8, 16), ClusterTopology.MAX_TOTAL_GPUS);
}

test "NodeInfo hostname" {
    var node = NodeInfo{ .node_id = 0 };
    node.setHostname("worker-0.cluster.local");
    
    try std.testing.expectEqualStrings("worker-0.cluster.local", node.getHostname());
}

test "ClusterCoordinator rank calculations" {
    var coordinator = ClusterCoordinator{
        .allocator = std.testing.allocator,
        .node_id = 2,
        .local_gpu_count = 4,
    };
    
    // Node 2, Local GPU 3 -> Global rank 11
    try std.testing.expectEqual(@as(u8, 11), coordinator.getGlobalRank(3));
    
    // Global rank 11 -> Node 2
    try std.testing.expectEqual(@as(u8, 2), coordinator.getNodeFromRank(11));
    
    // Global rank 11 -> Local GPU 3
    try std.testing.expectEqual(@as(u8, 3), coordinator.getLocalGpuFromRank(11));
    
    // Rank 11 is on node 2
    try std.testing.expect(coordinator.isLocalRank(11));
    
    // Rank 0 is NOT on node 2
    try std.testing.expect(!coordinator.isLocalRank(0));
}

test "ClusterWorkloadDistribution" {
    var coordinator = ClusterCoordinator{
        .allocator = std.testing.allocator,
        .world_size = 2,
        .node_id = 0,
        .local_gpu_count = 4,
    };
    
    // Set up two nodes with 4 GPUs each
    coordinator.nodes[0] = NodeInfo{ .node_id = 0, .gpu_count = 4 };
    coordinator.nodes[1] = NodeInfo{ .node_id = 1, .gpu_count = 4 };
    
    const dist = coordinator.distributeClusterWorkload(100);
    
    // Should have 8 tasks (4 GPUs × 2 nodes)
    try std.testing.expectEqual(@as(u8, 8), dist.task_count);
    
    // Verify total batch size is preserved
    var total: usize = 0;
    for (dist.getTasks()) |maybe_task| {
        if (maybe_task) |task| {
            total += task.batch_size;
        }
    }
    try std.testing.expectEqual(@as(usize, 100), total);
}