CREATE SCHEMA IF NOT EXISTS AI_GOVERNANCE;

CREATE COLUMN TABLE IF NOT EXISTS AI_GOVERNANCE.DIMENSION_FACTS (
    FACT_ID NVARCHAR(64) PRIMARY KEY,
    ACTION_NAME NVARCHAR(128),
    DIMENSION_NAME NVARCHAR(64) NOT NULL,
    DESCRIPTION NVARCHAR(500) NOT NULL,
    FRAMEWORK_ID NVARCHAR(64) DEFAULT 'MGF-Agentic-AI',
    FRAMEWORK_STATUS NVARCHAR(32) DEFAULT 'enforced',
    REVIEW_REQUIRED BOOLEAN DEFAULT TRUE,
    SOURCE NVARCHAR(64) DEFAULT 'seed',
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_UTCTIMESTAMP
);

CREATE COLUMN TABLE IF NOT EXISTS AI_GOVERNANCE.AUDIT_LOGS (
    TRACE_ID NVARCHAR(64) NOT NULL,
    SPAN_ID NVARCHAR(64) PRIMARY KEY,
    SERVICE NVARCHAR(128) NOT NULL,
    OPERATION NVARCHAR(256) NOT NULL,
    MODEL NVARCHAR(128),
    SECURITY_CLASS NVARCHAR(64) DEFAULT 'internal',
    MANGLE_RULES_JSON NCLOB,
    ROUTING_DECISION NVARCHAR(64),
    LATENCY_MS INTEGER DEFAULT 0,
    TTFT_MS INTEGER DEFAULT 0,
    TOKENS_IN INTEGER DEFAULT 0,
    TOKENS_OUT INTEGER DEFAULT 0,
    ACCEPTANCE_RATE DOUBLE DEFAULT 0,
    GDPR_SUBJECT_ID NVARCHAR(128),
    REGION NVARCHAR(64),
    OUTCOME NVARCHAR(32) DEFAULT 'allowed',
    TIMESTAMP_MS BIGINT NOT NULL,
    PAYLOAD_JSON NCLOB,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_UTCTIMESTAMP
);

CREATE COLUMN TABLE IF NOT EXISTS AI_GOVERNANCE.AUDIT_VECTOR_INDEX (
    DOC_ID NVARCHAR(64) PRIMARY KEY,
    CONTENT NCLOB NOT NULL,
    CONTENT_VECTOR REAL_VECTOR,
    METADATA_JSON NCLOB,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_UTCTIMESTAMP
);