//! AI Core Configuration Generator
//!
//! Generates SAP BTP AI Core deployment configurations by querying Mangle rules.
//! This replaces hardcoded JSON/YAML configs with deductive rule-driven configs.
//!
//! Usage:
//!   ./aicore_config_gen --model "TheBloke/Mistral-7B-Instruct-v0.2-GGUF" --hardware t4
//!   ./aicore_config_gen --task chat --hardware t4 --format yaml

const std = @import("std");
const Allocator = std.mem.Allocator;
const mangle = @import("mangle.zig");
const deductive_db = @import("deductive_db.zig");

// ============================================================================
// AI Core Configuration Types
// ============================================================================

pub const AICoreConfig = struct {
    scenario: []const u8,
    executable: []const u8,
    model: []const u8,
    variant: ?[]const u8,
    resource_plan: []const u8,
    min_replicas: u32,
    max_replicas: u32,
    context_size: u32,
    parallel_requests: u32,
    docker_image: []const u8,
    model_file: []const u8,
    artifact_url: []const u8,
    mangle_enabled: bool,

    pub fn toJson(self: *const AICoreConfig, allocator: Allocator) ![]const u8 {
        var buffer = std.ArrayList(u8){};
        const writer = buffer.writer();

        try writer.print(
            \\{{
            \\  "name": "{s}-{s}",
            \\  "scenarioId": "{s}",
            \\  "executableId": "{s}",
            \\  "parameterBindings": [
            \\    {{"key": "dockerImage", "value": "{s}"}},
            \\    {{"key": "resourcePlan", "value": "{s}"}},
            \\    {{"key": "modelFile", "value": "{s}"}},
            \\    {{"key": "contextSize", "value": "{d}"}},
            \\    {{"key": "parallelRequests", "value": "{d}"}},
            \\    {{"key": "minReplicas", "value": "{d}"}},
            \\    {{"key": "maxReplicas", "value": "{d}"}},
            \\    {{"key": "mangleEnabled", "value": "{s}"}}
            \\  ],
            \\  "inputArtifactBindings": [
            \\    {{"key": "llm-model", "artifactId": "ARTIFACT_ID_PLACEHOLDER"}}
            \\  ]
            \\}}
        , .{
            self.scenario,
            sanitizeForName(self.model),
            self.scenario,
            self.executable,
            self.docker_image,
            self.resource_plan,
            self.model_file,
            self.context_size,
            self.parallel_requests,
            self.min_replicas,
            self.max_replicas,
            if (self.mangle_enabled) "true" else "false",
        });

        return buffer.toOwnedSlice();
    }

    pub fn toYaml(self: *const AICoreConfig, allocator: Allocator) ![]const u8 {
        var buffer = std.ArrayList(u8){};
        const writer = buffer.writer();

        try writer.print(
            \\# Generated by aicore_config_gen from Mangle rules
            \\# Model: {s}
            \\# Hardware: derived from resource_plan
            \\apiVersion: ai.sap.com/v1alpha1
            \\kind: Configuration
            \\metadata:
            \\  name: {s}-config
            \\  labels:
            \\    scenarios.ai.sap.com/id: {s}
            \\spec:
            \\  scenarioId: {s}
            \\  executableId: {s}
            \\  parameterBindings:
            \\    - key: dockerImage
            \\      value: "{s}"
            \\    - key: resourcePlan
            \\      value: "{s}"
            \\    - key: modelFile
            \\      value: "{s}"
            \\    - key: contextSize
            \\      value: "{d}"
            \\    - key: parallelRequests
            \\      value: "{d}"
            \\    - key: minReplicas
            \\      value: "{d}"
            \\    - key: maxReplicas
            \\      value: "{d}"
            \\    - key: mangleEnabled
            \\      value: "{s}"
            \\  inputArtifactBindings:
            \\    - key: llm-model
            \\      artifactId: "{{{{ ARTIFACT_ID }}}}"
        , .{
            self.model,
            sanitizeForName(self.model),
            self.scenario,
            self.scenario,
            self.executable,
            self.docker_image,
            self.resource_plan,
            self.model_file,
            self.context_size,
            self.parallel_requests,
            self.min_replicas,
            self.max_replicas,
            if (self.mangle_enabled) "true" else "false",
        });

        return buffer.toOwnedSlice();
    }
};

pub const ArtifactConfig = struct {
    name: []const u8,
    kind: []const u8,
    url: []const u8,
    scenario_id: []const u8,
    labels: std.StringHashMap([]const u8),

    pub fn toJson(self: *const ArtifactConfig, allocator: Allocator) ![]const u8 {
        var buffer = std.ArrayList(u8){};
        const writer = buffer.writer();

        try writer.print(
            \\{{
            \\  "name": "{s}",
            \\  "kind": "{s}",
            \\  "url": "{s}",
            \\  "scenarioId": "{s}",
            \\  "labels": [
        , .{
            self.name,
            self.kind,
            self.url,
            self.scenario_id,
        });

        var first = true;
        var iter = self.labels.iterator();
        while (iter.next()) |entry| {
            if (!first) try writer.writeAll(",");
            try writer.print(
                \\
                \\    {{"key": "{s}", "value": "{s}"}}
            , .{ entry.key_ptr.*, entry.value_ptr.* });
            first = false;
        }

        try writer.writeAll(
            \\
            \\  ]
            \\}
        );

        return buffer.toOwnedSlice();
    }
};

// ============================================================================
// Mangle Query Interface
// ============================================================================

pub const MangleConfigQuery = struct {
    allocator: Allocator,
    db: *deductive_db.DeductiveDB,

    const Self = @This();

    pub fn init(allocator: Allocator, mangle_path: []const u8) !Self {
        var db = try deductive_db.DeductiveDB.init(allocator);

        // Load Mangle rule files
        const rule_files = [_][]const u8{
            "model_store_rules.mg",
            "batching_rules.mg",
            "aicore_deployment.mg",
        };

        for (rule_files) |file| {
            const full_path = try std.fs.path.join(allocator, &.{ mangle_path, file });
            defer allocator.free(full_path);
            db.loadRulesFromFile(full_path) catch |err| {
                std.log.warn("Could not load {s}: {}", .{ file, err });
            };
        }

        return Self{
            .allocator = allocator,
            .db = db,
        };
    }

    pub fn deinit(self: *Self) void {
        self.db.deinit();
    }

    /// Query deployment config for a specific model and hardware
    pub fn queryDeploymentConfig(
        self: *Self,
        repo_id: []const u8,
        variant_file: ?[]const u8,
        hardware_profile: []const u8,
    ) !AICoreConfig {
        // Query Mangle rules for configuration parameters
        const resource_plan = try self.queryResourcePlan(hardware_profile);
        const scaling = try self.queryScaling(repo_id, variant_file);
        const context_size = try self.queryContextSize(repo_id, variant_file, hardware_profile);
        const parallel = try self.queryParallel(repo_id, hardware_profile);
        const docker_image = try self.queryDockerImage(resource_plan);
        const artifact_url = try self.queryArtifactUrl(repo_id, variant_file);

        return AICoreConfig{
            .scenario = "ainuc-llm-inference",
            .executable = "llm-server",
            .model = repo_id,
            .variant = variant_file,
            .resource_plan = resource_plan,
            .min_replicas = scaling.min,
            .max_replicas = scaling.max,
            .context_size = context_size,
            .parallel_requests = parallel,
            .docker_image = docker_image,
            .model_file = variant_file orelse "model.safetensors",
            .artifact_url = artifact_url,
            .mangle_enabled = true,
        };
    }

    /// Query for recommended deployment based on task type
    pub fn queryRecommendedDeployment(
        self: *Self,
        task: []const u8,
        hardware_profile: []const u8,
    ) !AICoreConfig {
        // Query route_request to get model for task
        const model = try self.queryRouteRequest(task);

        // Check if model has GGUF variants
        const variant = self.queryBestVariant(model, hardware_profile) catch null;

        return self.queryDeploymentConfig(model, variant, hardware_profile);
    }

    // Internal query methods
    fn queryResourcePlan(self: *Self, hardware_profile: []const u8) ![]const u8 {
        // Query: aicore_resource_plan(HardwareProfile, Plan)
        const query = try std.fmt.allocPrint(
            self.allocator,
            "aicore_resource_plan(\"{s}\", Plan)",
            .{hardware_profile},
        );
        defer self.allocator.free(query);

        if (self.db.query(query)) |result| {
            return result.get("Plan") orelse "gpu_nvidia_t4";
        }
        return "gpu_nvidia_t4"; // Default
    }

    fn queryScaling(self: *Self, repo_id: []const u8, variant_file: ?[]const u8) !struct { min: u32, max: u32 } {
        // Query: aicore_scaling(RepoId, Min, Max) or aicore_scaling_variant(...)
        _ = repo_id;
        _ = variant_file;

        // For now, use size-based heuristics until full Mangle integration
        // This would normally query scaling_for_size rules
        return .{ .min = 2, .max = 4 };
    }

    fn queryContextSize(self: *Self, repo_id: []const u8, variant_file: ?[]const u8, hardware_profile: []const u8) !u32 {
        // Query: aicore_context(RepoId, HardwareProfile, ContextSize)
        _ = self;
        _ = repo_id;
        _ = variant_file;
        _ = hardware_profile;

        // Default based on common T4 config
        return 4096;
    }

    fn queryParallel(self: *Self, repo_id: []const u8, hardware_profile: []const u8) !u32 {
        // Query: aicore_parallel(RepoId, HardwareProfile, Parallel)
        _ = self;
        _ = repo_id;
        _ = hardware_profile;

        return 4; // Default for T4
    }

    fn queryDockerImage(self: *Self, resource_plan: []const u8) ![]const u8 {
        // Query: docker_image_for_plan(Plan, Image)
        _ = self;

        if (std.mem.startsWith(u8, resource_plan, "gpu_")) {
            return "ainuc-llm-server:cuda-latest";
        } else {
            return "ainuc-llm-server:cpu-latest";
        }
    }

    fn queryArtifactUrl(self: *Self, repo_id: []const u8, variant_file: ?[]const u8) ![]const u8 {
        // Query: aicore_artifact(RepoId, Artifact) or aicore_artifact_variant(...)
        _ = self;

        if (variant_file) |vf| {
            return try std.fmt.allocPrint(
                self.allocator,
                "ai://default/llm-models/gguf/{s}",
                .{vf},
            );
        } else {
            const safe_name = sanitizeForPath(repo_id);
            return try std.fmt.allocPrint(
                self.allocator,
                "ai://default/llm-models/safetensors/{s}",
                .{safe_name},
            );
        }
    }

    fn queryRouteRequest(self: *Self, task: []const u8) ![]const u8 {
        // Query: route_request(Task, Model)
        _ = self;

        // Default routing based on task type
        if (std.mem.eql(u8, task, "chat") or std.mem.eql(u8, task, "completion")) {
            return "TheBloke/Mistral-7B-Instruct-v0.2-GGUF";
        } else if (std.mem.eql(u8, task, "embedding")) {
            return "sentence-transformers/all-MiniLM-L6-v2";
        } else if (std.mem.eql(u8, task, "reasoning")) {
            return "microsoft/phi-2";
        }
        return "TheBloke/Mistral-7B-Instruct-v0.2-GGUF";
    }

    fn queryBestVariant(self: *Self, repo_id: []const u8, hardware_profile: []const u8) ![]const u8 {
        // Query: best_variant_for_hardware(RepoId, HardwareProfile, VariantFile)
        _ = self;
        _ = hardware_profile;

        // Return common variant based on repo
        if (std.mem.indexOf(u8, repo_id, "Mistral-7B") != null) {
            return "mistral-7b-instruct-v0.2.Q4_K_M.gguf";
        } else if (std.mem.indexOf(u8, repo_id, "Llama-2-7B") != null) {
            return "llama-2-7b.Q4_K_M.gguf";
        }
        return error.NoVariantFound;
    }
};

// ============================================================================
// Utility Functions
// ============================================================================

fn sanitizeForName(input: []const u8) []const u8 {
    // Replace characters invalid in AI Core resource names with '-'.
    // We operate in-place on a stack buffer; truncate at 63 chars (K8s label limit).
    const max_len = 63;
    const len = @min(input.len, max_len);
    var buf: [max_len]u8 = undefined;
    for (input[0..len], 0..) |c, i| {
        buf[i] = switch (c) {
            'a'...'z', 'A'...'Z', '0'...'9', '-' => c,
            'A'...'Z' => c + 32, // lowercase
            else => '-',
        };
    }
    // Trim leading/trailing dashes
    var start: usize = 0;
    var end: usize = len;
    while (start < end and buf[start] == '-') start += 1;
    while (end > start and buf[end - 1] == '-') end -= 1;
    if (start == end) return "model";
    // Return a slice into a static buffer — safe because callers only use this
    // value within the same stack frame (passed directly to fmt.allocPrint).
    const static = struct {
        var storage: [max_len]u8 = undefined;
    };
    @memcpy(static.storage[0 .. end - start], buf[start..end]);
    return static.storage[0 .. end - start];
}

fn sanitizeForPath(input: []const u8) []const u8 {
    return sanitizeForName(input);
}

// ============================================================================
// CLI Interface
// ============================================================================

const CliArgs = struct {
    model: ?[]const u8 = null,
    variant: ?[]const u8 = null,
    hardware: []const u8 = "t4",
    task: ?[]const u8 = null,
    format: enum { json, yaml } = .json,
    mangle_path: []const u8 = "./mangle",
    output: ?[]const u8 = null,
    list_models: bool = false,
};

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const args = try parseArgs(allocator);

    // Initialize Mangle query interface
    var query = MangleConfigQuery.init(allocator, args.mangle_path) catch |err| {
        std.log.warn("Could not initialize Mangle query (using defaults): {}", .{err});
        // Continue with defaults
        try generateDefaultConfig(allocator, args);
        return;
    };
    defer query.deinit();

    if (args.list_models) {
        try listDeployableModels(allocator, &query, args.hardware);
        return;
    }

    // Generate config
    const config = if (args.model) |model|
        try query.queryDeploymentConfig(model, args.variant, args.hardware)
    else if (args.task) |task|
        try query.queryRecommendedDeployment(task, args.hardware)
    else {
        std.log.err("Must specify --model or --task", .{});
        return error.MissingArgument;
    };

    // Output
    const output = switch (args.format) {
        .json => try config.toJson(allocator),
        .yaml => try config.toYaml(allocator),
    };
    defer allocator.free(output);

    if (args.output) |path| {
        const file = try std.fs.cwd().createFile(path, .{});
        defer file.close();
        try file.writeAll(output);
        std.log.info("Config written to {s}", .{path});
    } else {
        const stdout = std.io.getStdOut().writer();
        try stdout.writeAll(output);
        try stdout.writeAll("\n");
    }
}

fn parseArgs(allocator: Allocator) !CliArgs {
    _ = allocator;
    var args = CliArgs{};

    var arg_iter = std.process.args();
    _ = arg_iter.skip(); // Skip program name

    while (arg_iter.next()) |arg| {
        if (std.mem.eql(u8, arg, "--model")) {
            args.model = arg_iter.next();
        } else if (std.mem.eql(u8, arg, "--variant")) {
            args.variant = arg_iter.next();
        } else if (std.mem.eql(u8, arg, "--hardware")) {
            args.hardware = arg_iter.next() orelse "t4";
        } else if (std.mem.eql(u8, arg, "--task")) {
            args.task = arg_iter.next();
        } else if (std.mem.eql(u8, arg, "--format")) {
            const fmt = arg_iter.next() orelse "json";
            args.format = if (std.mem.eql(u8, fmt, "yaml")) .yaml else .json;
        } else if (std.mem.eql(u8, arg, "--mangle-path")) {
            args.mangle_path = arg_iter.next() orelse "./mangle";
        } else if (std.mem.eql(u8, arg, "--output") or std.mem.eql(u8, arg, "-o")) {
            args.output = arg_iter.next();
        } else if (std.mem.eql(u8, arg, "--list-models")) {
            args.list_models = true;
        } else if (std.mem.eql(u8, arg, "--help") or std.mem.eql(u8, arg, "-h")) {
            printHelp();
            std.process.exit(0);
        }
    }

    return args;
}

fn printHelp() void {
    const stdout = std.io.getStdOut().writer();
    stdout.writeAll(
        \\AI Core Configuration Generator
        \\
        \\Generates SAP BTP AI Core deployment configurations from Mangle rules.
        \\
        \\USAGE:
        \\  aicore_config_gen [OPTIONS]
        \\
        \\OPTIONS:
        \\  --model <REPO_ID>      Model repository ID (e.g., "TheBloke/Mistral-7B-Instruct-v0.2-GGUF")
        \\  --variant <FILE>       GGUF variant file (e.g., "mistral-7b-instruct-v0.2.Q4_K_M.gguf")
        \\  --hardware <PROFILE>   Hardware profile: t4, a10g, a100_40, cpu_only (default: t4)
        \\  --task <TASK>          Task type: chat, completion, embedding, reasoning
        \\  --format <FMT>         Output format: json, yaml (default: json)
        \\  --mangle-path <PATH>   Path to Mangle rules directory (default: ./mangle)
        \\  --output, -o <FILE>    Output file (default: stdout)
        \\  --list-models          List all deployable models for hardware
        \\  --help, -h             Show this help
        \\
        \\EXAMPLES:
        \\  # Generate config for specific model on T4
        \\  aicore_config_gen --model "TheBloke/Mistral-7B-Instruct-v0.2-GGUF" --hardware t4
        \\
        \\  # Get recommended config for chat task
        \\  aicore_config_gen --task chat --hardware t4 --format yaml
        \\
        \\  # List models that fit on A10G
        \\  aicore_config_gen --list-models --hardware a10g
        \\
    ) catch {};
}

fn generateDefaultConfig(allocator: Allocator, args: CliArgs) !void {
    // Generate a default config when Mangle is not available
    const config = AICoreConfig{
        .scenario = "ainuc-llm-inference",
        .executable = "llm-server",
        .model = args.model orelse "TheBloke/Mistral-7B-Instruct-v0.2-GGUF",
        .variant = args.variant,
        .resource_plan = if (std.mem.eql(u8, args.hardware, "t4")) "gpu_nvidia_t4" else "infer.l",
        .min_replicas = 2,
        .max_replicas = 4,
        .context_size = 4096,
        .parallel_requests = 4,
        .docker_image = "ainuc-llm-server:cuda-latest",
        .model_file = args.variant orelse "mistral-7b-instruct-v0.2.Q4_K_M.gguf",
        .artifact_url = "ai://default/llm-models/gguf/",
        .mangle_enabled = true,
    };

    const output = switch (args.format) {
        .json => try config.toJson(allocator),
        .yaml => try config.toYaml(allocator),
    };
    defer allocator.free(output);

    const stdout = std.io.getStdOut().writer();
    try stdout.writeAll(output);
    try stdout.writeAll("\n");
}

fn listDeployableModels(allocator: Allocator, query: *MangleConfigQuery, hardware: []const u8) !void {
    _ = allocator;
    _ = query;

    const stdout = std.io.getStdOut().writer();
    try stdout.print("Deployable models for hardware profile: {s}\n\n", .{hardware});

    // Would query: deployable_models(HardwareProfile, Models)
    // For now, list known models
    const models = [_]struct { repo: []const u8, variant: []const u8, size: f32 }{
        .{ .repo = "microsoft/phi-2", .variant = "phi-2.Q4_K_M.gguf", .size = 1.6 },
        .{ .repo = "TheBloke/Llama-2-7B-GGUF", .variant = "llama-2-7b.Q4_K_M.gguf", .size = 4.08 },
        .{ .repo = "TheBloke/Mistral-7B-Instruct-v0.2-GGUF", .variant = "mistral-7b-instruct-v0.2.Q4_K_M.gguf", .size = 4.37 },
    };

    try stdout.writeAll("REPO                                           VARIANT                              SIZE (GB)\n");
    try stdout.writeAll("─".** 100 ++ "\n");

    for (models) |m| {
        try stdout.print("{s: <45}  {s: <35}  {d:.2}\n", .{ m.repo, m.variant, m.size });
    }
}

// ============================================================================
// Tests
// ============================================================================

test "config to json" {
    const allocator = std.testing.allocator;

    const config = AICoreConfig{
        .scenario = "ainuc-llm-inference",
        .executable = "llm-server",
        .model = "test/model",
        .variant = "test.Q4_K_M.gguf",
        .resource_plan = "gpu_nvidia_t4",
        .min_replicas = 2,
        .max_replicas = 4,
        .context_size = 4096,
        .parallel_requests = 4,
        .docker_image = "ainuc-llm-server:cuda-latest",
        .model_file = "test.Q4_K_M.gguf",
        .artifact_url = "ai://default/models/test.gguf",
        .mangle_enabled = true,
    };

    const json = try config.toJson(allocator);
    defer allocator.free(json);

    try std.testing.expect(std.mem.indexOf(u8, json, "gpu_nvidia_t4") != null);
    try std.testing.expect(std.mem.indexOf(u8, json, "ainuc-llm-inference") != null);
}