FROM node:20-slim AS build

WORKDIR /workspace

RUN corepack enable

COPY package.json yarn.lock .yarnrc.yml ./
COPY .yarn ./.yarn
RUN yarn install --immutable

COPY . .
RUN yarn nx build playground --configuration=production --base-href /ui5/

FROM nginx:1.27-alpine

COPY docker/nginx-suite-web.conf /etc/nginx/conf.d/default.conf
COPY --from=build /workspace/dist/apps/playground /usr/share/nginx/html

EXPOSE 80
