const std = @import("std");
const pal = @import("../domain/pal.zig");

// ============================================================================
// HANA SQL CALL Generator — produces SQLScript for PAL procedure execution
// ============================================================================

pub const ParamType = enum { integer, double, string };

pub const Param = struct {
    name: []const u8,
    param_type: ParamType,
    value: []const u8,
};

pub fn generateCall(
    allocator: std.mem.Allocator,
    alg: *const pal.Algorithm,
    table_name: []const u8,
    params: []const Param,
) ![]const u8 {
    var buf: std.ArrayList(u8) = .{};
    const w = buf.writer(allocator);

    try w.writeAll("-- ============================================================================\n");
    try w.print("-- PAL CALL: {s}\n", .{alg.name});
    try w.print("-- Procedure: {s}\n", .{alg.procedure});
    try w.print("-- Generated by mcppal-mesh-gateway\n", .{});
    try w.writeAll("-- ============================================================================\n\n");

    try w.writeAll("DO BEGIN\n");
    try w.writeAll("    DECLARE lt_param TABLE (\n");
    try w.writeAll("        PARAM_NAME VARCHAR(256),\n");
    try w.writeAll("        INT_VALUE INTEGER,\n");
    try w.writeAll("        DOUBLE_VALUE DOUBLE,\n");
    try w.writeAll("        STRING_VALUE NVARCHAR(1000)\n");
    try w.writeAll("    );\n\n");

    // Insert parameters
    for (params) |p| {
        switch (p.param_type) {
            .integer => try w.print("    INSERT INTO :lt_param VALUES ('{s}', {s}, NULL, NULL);\n", .{ p.name, p.value }),
            .double => try w.print("    INSERT INTO :lt_param VALUES ('{s}', NULL, {s}, NULL);\n", .{ p.name, p.value }),
            .string => try w.print("    INSERT INTO :lt_param VALUES ('{s}', NULL, NULL, '{s}');\n", .{ p.name, p.value }),
        }
    }

    try w.writeAll("\n");
    try w.print("    CALL {s}(\n", .{alg.procedure});
    try w.print("        {s},\n", .{table_name});
    try w.writeAll("        :lt_param,\n");
    try w.writeAll("        lt_result\n");
    try w.writeAll("    ) WITH OVERVIEW;\n\n");
    try w.writeAll("    SELECT * FROM :lt_result;\n");
    try w.writeAll("END;\n");

    return buf.toOwnedSlice(allocator);
}

// ============================================================================
// Tests
// ============================================================================

test "generateCall produces DO BEGIN block" {
    const allocator = std.testing.allocator;
    const alg = pal.Algorithm{
        .id = "kmeans",
        .name = "K-Means",
        .category = "clustering",
        .module = "PAL",
        .procedure = "_SYS_AFL.PAL_KMEANS",
        .stability = "stable",
        .version = "2.0",
    };
    const sql = try generateCall(allocator, &alg, "MY_TABLE", &.{});
    defer allocator.free(sql);

    try std.testing.expect(std.mem.indexOf(u8, sql, "DO BEGIN") != null);
    try std.testing.expect(std.mem.indexOf(u8, sql, "END;") != null);
    try std.testing.expect(std.mem.indexOf(u8, sql, "_SYS_AFL.PAL_KMEANS") != null);
    try std.testing.expect(std.mem.indexOf(u8, sql, "MY_TABLE") != null);
}

test "generateCall emits integer param row" {
    const allocator = std.testing.allocator;
    const alg = pal.Algorithm{
        .id = "kmeans",
        .name = "K-Means",
        .category = "clustering",
        .module = "PAL",
        .procedure = "_SYS_AFL.PAL_KMEANS",
        .stability = "stable",
        .version = "2.0",
    };
    const params = [_]Param{
        .{ .name = "GROUP_NUMBER", .param_type = .integer, .value = "5" },
    };
    const sql = try generateCall(allocator, &alg, "DATA", &params);
    defer allocator.free(sql);

    try std.testing.expect(std.mem.indexOf(u8, sql, "'GROUP_NUMBER', 5, NULL, NULL") != null);
}

test "generateCall emits double param row" {
    const allocator = std.testing.allocator;
    const alg = pal.Algorithm{
        .id = "arima",
        .name = "ARIMA",
        .category = "timeseries",
        .module = "PAL",
        .procedure = "_SYS_AFL.PAL_ARIMA",
        .stability = "stable",
        .version = "1.0",
    };
    const params = [_]Param{
        .{ .name = "THRESHOLD", .param_type = .double, .value = "0.95" },
    };
    const sql = try generateCall(allocator, &alg, "TS_DATA", &params);
    defer allocator.free(sql);

    try std.testing.expect(std.mem.indexOf(u8, sql, "'THRESHOLD', NULL, 0.95, NULL") != null);
}

test "generateCall emits string param row" {
    const allocator = std.testing.allocator;
    const alg = pal.Algorithm{
        .id = "naive_bayes",
        .name = "Naive Bayes",
        .category = "classification",
        .module = "PAL",
        .procedure = "_SYS_AFL.PAL_NAIVE_BAYES",
        .stability = "stable",
        .version = "1.0",
    };
    const params = [_]Param{
        .{ .name = "LAPLACE", .param_type = .string, .value = "auto" },
    };
    const sql = try generateCall(allocator, &alg, "TRAIN", &params);
    defer allocator.free(sql);

    try std.testing.expect(std.mem.indexOf(u8, sql, "'LAPLACE', NULL, NULL, 'auto'") != null);
}

test "generateCall with no params still calls procedure" {
    const allocator = std.testing.allocator;
    const alg = pal.Algorithm{
        .id = "pca",
        .name = "PCA",
        .category = "preprocessing",
        .module = "PAL",
        .procedure = "_SYS_AFL.PAL_PCA",
        .stability = "stable",
        .version = "1.0",
    };
    const sql = try generateCall(allocator, &alg, "INPUT_DATA", &.{});
    defer allocator.free(sql);

    try std.testing.expect(std.mem.indexOf(u8, sql, "CALL _SYS_AFL.PAL_PCA") != null);
    try std.testing.expect(std.mem.indexOf(u8, sql, "SELECT * FROM :lt_result;") != null);
}

pub fn generateCallFromArgs(
    allocator: std.mem.Allocator,
    alg: *const pal.Algorithm,
    args: std.json.Value,
) ![]const u8 {
    const table_name = if (args == .object)
        if (args.object.get("table")) |t| switch (t) {
            .string => |s| s,
            else => "INPUT_DATA",
        }
    else
        "INPUT_DATA"
    else
        "INPUT_DATA";

    var params: std.ArrayList(Param) = .{};
    defer params.deinit(allocator);

    if (args == .object) {
        if (args.object.get("params")) |p| {
            if (p == .object) {
                var it = p.object.iterator();
                while (it.next()) |entry| {
                    const val_str = switch (entry.value_ptr.*) {
                        .string => |s| s,
                        .integer => |i| try std.fmt.allocPrint(allocator, "{d}", .{i}),
                        .float => |f| try std.fmt.allocPrint(allocator, "{d}", .{f}),
                        else => continue,
                    };
                    const pt: ParamType = switch (entry.value_ptr.*) {
                        .integer => .integer,
                        .float => .double,
                        else => .string,
                    };
                    try params.append(allocator, .{
                        .name = entry.key_ptr.*,
                        .param_type = pt,
                        .value = val_str,
                    });
                }
            }
        }
    }

    return generateCall(allocator, alg, table_name, params.items);
}
