"""
LLM Fact Validation Gateway (H1 Implementation)

This module validates facts generated by LLMs before they can be asserted
into the Mangle knowledge base. It implements the validation flow described
in the safety-ai-governance.pdf paper:

1. Parse LLM output into candidate facts
2. Validate each fact against:
   - Schema constraints (predicate arity, type checking)
   - Domain constraints (allowed predicates, value ranges)
   - Safety invariants (via Mangle rule evaluation)
3. Only allow validated facts to be asserted

Reference: safety-ndeductivedatabase-mangle.pdf Section 8 (Stratification & Safety)
"""

from collections import Dict, Set
from memory import UnsafePointer
from memory.unsafe_pointer import alloc
from time import now

# Import base parser
from .parser import MangleFact, MangleParser


# =============================================================================
# VALIDATION RESULT TYPES
# =============================================================================

struct ValidationResult:
    """Result of validating a single fact."""
    var is_valid: Bool
    var fact: MangleFact
    var error_code: String
    var error_message: String
    var confidence: Float32
    var validation_time_ns: Int
    
    fn __init__(out self, fact: MangleFact):
        self.is_valid = False
        self.fact = fact
        self.error_code = ""
        self.error_message = ""
        self.confidence = 0.0
        self.validation_time_ns = 0
    
    fn set_valid(mut self, confidence: Float32):
        self.is_valid = True
        self.confidence = confidence
        self.error_code = ""
        self.error_message = ""
    
    fn set_invalid(mut self, code: String, message: String):
        self.is_valid = False
        self.error_code = code
        self.error_message = message
        self.confidence = 0.0


struct BatchValidationResult:
    """Result of validating multiple facts."""
    var results: List[ValidationResult]
    var total_count: Int
    var valid_count: Int
    var invalid_count: Int
    var total_time_ns: Int
    
    fn __init__(out self):
        self.results = List[ValidationResult]()
        self.total_count = 0
        self.valid_count = 0
        self.invalid_count = 0
        self.total_time_ns = 0
    
    fn add_result(mut self, result: ValidationResult):
        if result.is_valid:
            self.valid_count += 1
        else:
            self.invalid_count += 1
        self.total_count += 1
        self.total_time_ns += result.validation_time_ns
        self.results.append(result)
    
    fn acceptance_rate(self) -> Float32:
        if self.total_count == 0:
            return 0.0
        return Float32(self.valid_count) / Float32(self.total_count)


# =============================================================================
# PREDICATE SCHEMA REGISTRY
# =============================================================================

struct PredicateSchema:
    """Schema definition for a Mangle predicate."""
    var name: String
    var arity: Int
    var arg_types: List[String]  # "string", "int", "float", "bool", "any"
    var is_llm_writable: Bool    # Can LLM assert this predicate?
    var requires_evidence: Bool  # Must have provenance/source?
    var confidence_threshold: Float32  # Minimum confidence to assert
    
    fn __init__(out self, name: String, arity: Int):
        self.name = name
        self.arity = arity
        self.arg_types = List[String]()
        self.is_llm_writable = True
        self.requires_evidence = False
        self.confidence_threshold = 0.0
    
    fn with_arg_type(mut self, arg_type: String) -> Self:
        """Builder pattern for adding argument types."""
        self.arg_types.append(arg_type)
        return self
    
    fn llm_writable(mut self, writable: Bool) -> Self:
        self.is_llm_writable = writable
        return self
    
    fn evidence_required(mut self, required: Bool) -> Self:
        self.requires_evidence = required
        return self
    
    fn min_confidence(mut self, threshold: Float32) -> Self:
        self.confidence_threshold = threshold
        return self


struct SchemaRegistry:
    """Registry of allowed predicate schemas."""
    var schemas: List[PredicateSchema]
    var allowed_predicates: Set[String]
    var llm_writable_predicates: Set[String]
    
    fn __init__(out self):
        self.schemas = List[PredicateSchema]()
        self.allowed_predicates = Set[String]()
        self.llm_writable_predicates = Set[String]()
        
        # Initialize with core safety schemas
        self._register_safety_schemas()
    
    fn _register_safety_schemas(mut self):
        """Register built-in safety-related predicate schemas."""
        
        # From ai_safety_facts.mg - safety assessment predicates
        var safety_assessment = PredicateSchema("safety_assessment", 4)
        safety_assessment = safety_assessment.with_arg_type("string")  # request_id
        safety_assessment = safety_assessment.with_arg_type("string")  # category
        safety_assessment = safety_assessment.with_arg_type("string")  # level
        safety_assessment = safety_assessment.with_arg_type("float")   # confidence
        safety_assessment = safety_assessment.min_confidence(0.8)
        self.register(safety_assessment)
        
        # Entity extraction - lower threshold for LLM output
        var entity_extracted = PredicateSchema("entity_extracted", 4)
        entity_extracted = entity_extracted.with_arg_type("string")  # request_id
        entity_extracted = entity_extracted.with_arg_type("string")  # entity_type
        entity_extracted = entity_extracted.with_arg_type("string")  # value
        entity_extracted = entity_extracted.with_arg_type("float")   # confidence
        entity_extracted = entity_extracted.min_confidence(0.6)
        self.register(entity_extracted)
        
        # Intent classification
        var intent_classified = PredicateSchema("intent_classified", 3)
        intent_classified = intent_classified.with_arg_type("string")  # request_id
        intent_classified = intent_classified.with_arg_type("string")  # intent
        intent_classified = intent_classified.with_arg_type("float")   # confidence
        intent_classified = intent_classified.min_confidence(0.7)
        self.register(intent_classified)
        
        # Fact extraction from documents (evidence required)
        var fact_from_document = PredicateSchema("fact_from_document", 5)
        fact_from_document = fact_from_document.with_arg_type("string")  # fact_id
        fact_from_document = fact_from_document.with_arg_type("string")  # subject
        fact_from_document = fact_from_document.with_arg_type("string")  # predicate
        fact_from_document = fact_from_document.with_arg_type("string")  # object
        fact_from_document = fact_from_document.with_arg_type("string")  # source_doc
        fact_from_document = fact_from_document.evidence_required(True)
        fact_from_document = fact_from_document.min_confidence(0.75)
        self.register(fact_from_document)
        
        # Model capability assertions - NOT writable by LLM
        var model_capability = PredicateSchema("model_has_capability", 2)
        model_capability = model_capability.with_arg_type("string")
        model_capability = model_capability.with_arg_type("string")
        model_capability = model_capability.llm_writable(False)
        self.register(model_capability)
        
        # Policy facts - NOT writable by LLM (system-defined only)
        var policy_fact = PredicateSchema("policy", 3)
        policy_fact = policy_fact.with_arg_type("string")
        policy_fact = policy_fact.with_arg_type("string")
        policy_fact = policy_fact.with_arg_type("any")
        policy_fact = policy_fact.llm_writable(False)
        self.register(policy_fact)
    
    fn register(mut self, schema: PredicateSchema):
        """Register a predicate schema."""
        self.allowed_predicates.add(schema.name)
        if schema.is_llm_writable:
            self.llm_writable_predicates.add(schema.name)
        self.schemas.append(schema)
    
    fn get_schema(self, predicate: String) -> UnsafePointer[PredicateSchema]:
        """Look up schema by predicate name."""
        for i in range(len(self.schemas)):
            if self.schemas[i].name == predicate:
                return UnsafePointer.address_of(self.schemas[i])
        return UnsafePointer[PredicateSchema]()
    
    fn is_allowed(self, predicate: String) -> Bool:
        """Check if predicate is in registry."""
        return predicate in self.allowed_predicates
    
    fn is_llm_writable(self, predicate: String) -> Bool:
        """Check if LLM can assert this predicate."""
        return predicate in self.llm_writable_predicates


# =============================================================================
# FACT VALIDATORS
# =============================================================================

struct SchemaValidator:
    """Validates facts against predicate schemas."""
    var registry: SchemaRegistry
    
    fn __init__(out self, registry: SchemaRegistry):
        self.registry = registry
    
    fn validate(self, fact: MangleFact, confidence: Float32) -> ValidationResult:
        """Validate a fact against its schema."""
        var result = ValidationResult(fact)
        
        # Check if predicate is registered
        if not self.registry.is_allowed(fact.predicate):
            result.set_invalid("UNKNOWN_PREDICATE", 
                "Predicate '" + fact.predicate + "' is not registered")
            return result
        
        # Check if LLM can write this predicate
        if not self.registry.is_llm_writable(fact.predicate):
            result.set_invalid("NOT_LLM_WRITABLE",
                "Predicate '" + fact.predicate + "' cannot be asserted by LLM")
            return result
        
        # Get schema
        var schema_ptr = self.registry.get_schema(fact.predicate)
        if not schema_ptr:
            result.set_invalid("NO_SCHEMA", "Schema not found")
            return result
        
        var schema = schema_ptr[]
        
        # Check arity
        if fact.num_args != schema.arity:
            result.set_invalid("ARITY_MISMATCH",
                "Expected " + String(schema.arity) + " args, got " + String(fact.num_args))
            return result
        
        # Check confidence threshold
        if confidence < schema.confidence_threshold:
            result.set_invalid("LOW_CONFIDENCE",
                "Confidence " + String(confidence) + " below threshold " + 
                String(schema.confidence_threshold))
            return result
        
        # Check argument types
        for i in range(min(len(schema.arg_types), fact.num_args)):
            var expected_type = schema.arg_types[i]
            var arg_value = fact.get_arg(i)
            
            if not self._check_type(arg_value, expected_type):
                result.set_invalid("TYPE_ERROR",
                    "Argument " + String(i) + " type mismatch: expected " + expected_type)
                return result
        
        # All checks passed
        result.set_valid(confidence)
        return result
    
    fn _check_type(self, value: String, expected: String) -> Bool:
        """Check if value matches expected type."""
        if expected == "any":
            return True
        
        if expected == "string":
            return True  # All values are strings in Mangle
        
        if expected == "int":
            try:
                _ = int(value)
                return True
            except:
                return False
        
        if expected == "float":
            try:
                _ = float(value)
                return True
            except:
                return False
        
        if expected == "bool":
            return value == "true" or value == "false"
        
        return True  # Unknown types pass


struct SafetyInvariantValidator:
    """Validates facts against safety invariants via Mangle evaluation."""
    var known_facts: List[MangleFact]
    
    fn __init__(out self):
        self.known_facts = List[MangleFact]()
    
    fn add_known_fact(mut self, fact: MangleFact):
        """Add a known fact for invariant checking."""
        self.known_facts.append(fact)
    
    fn validate(self, fact: MangleFact) -> ValidationResult:
        """
        Validate fact against safety invariants.
        
        Checks:
        1. No contradiction with existing facts
        2. No violation of safety rules
        3. Provenance exists if required
        """
        var result = ValidationResult(fact)
        var start_time = now()
        
        # Check for contradictions
        if self._contradicts_existing(fact):
            result.set_invalid("CONTRADICTION",
                "Fact contradicts existing knowledge")
            result.validation_time_ns = now() - start_time
            return result
        
        # Check safety invariants
        var safety_violation = self._check_safety_invariants(fact)
        if len(safety_violation) > 0:
            result.set_invalid("SAFETY_VIOLATION", safety_violation)
            result.validation_time_ns = now() - start_time
            return result
        
        # Valid
        result.set_valid(1.0)
        result.validation_time_ns = now() - start_time
        return result
    
    fn _contradicts_existing(self, fact: MangleFact) -> Bool:
        """Check if fact contradicts existing facts."""
        # Simple contradiction check: same predicate + args with negation
        for i in range(len(self.known_facts)):
            var existing = self.known_facts[i]
            
            # Check for direct negation pattern
            if fact.predicate == "not_" + existing.predicate:
                if self._args_match(fact, existing):
                    return True
            
            if existing.predicate == "not_" + fact.predicate:
                if self._args_match(fact, existing):
                    return True
        
        return False
    
    fn _args_match(self, f1: MangleFact, f2: MangleFact) -> Bool:
        """Check if fact arguments match."""
        if f1.num_args != f2.num_args:
            return False
        for i in range(f1.num_args):
            if f1.get_arg(i) != f2.get_arg(i):
                return False
        return True
    
    fn _check_safety_invariants(self, fact: MangleFact) -> String:
        """
        Check safety invariants for the fact.
        
        Returns empty string if valid, error message if violated.
        """
        # Invariant 1: Cannot assert unsafe content
        if fact.predicate == "safe_to_execute":
            # Check that the target actually passed safety review
            var target_id = fact.get_arg(0)
            var has_review = False
            for i in range(len(self.known_facts)):
                if self.known_facts[i].predicate == "safety_review_passed":
                    if self.known_facts[i].get_arg(0) == target_id:
                        has_review = True
                        break
            if not has_review:
                return "Cannot assert safe_to_execute without safety_review_passed"
        
        # Invariant 2: Cannot grant elevated permissions via LLM
        if fact.predicate == "has_permission":
            var permission = fact.get_arg(1) if fact.num_args > 1 else ""
            if permission in ["admin", "root", "system", "elevated"]:
                return "Cannot grant elevated permissions through LLM assertion"
        
        # Invariant 3: Cannot modify safety policy
        if fact.predicate.startswith("safety_policy_"):
            return "Cannot modify safety policies through LLM assertion"
        
        return ""


# =============================================================================
# MAIN VALIDATION GATEWAY
# =============================================================================

struct LLMFactValidationGateway:
    """
    Main validation gateway for LLM-generated facts.
    
    This is the H1 implementation from the safety-ai-governance paper.
    All facts from LLM outputs must pass through this gateway before
    being asserted into the Mangle knowledge base.
    """
    var schema_registry: SchemaRegistry
    var schema_validator: SchemaValidator
    var safety_validator: SafetyInvariantValidator
    var parser: MangleParser
    var facts_validated: Int
    var facts_rejected: Int
    var total_validation_time_ns: Int
    
    fn __init__(out self):
        self.schema_registry = SchemaRegistry()
        self.schema_validator = SchemaValidator(self.schema_registry)
        self.safety_validator = SafetyInvariantValidator()
        self.parser = MangleParser()
        self.facts_validated = 0
        self.facts_rejected = 0
        self.total_validation_time_ns = 0
    
    fn register_schema(mut self, schema: PredicateSchema):
        """Register a new predicate schema."""
        self.schema_registry.register(schema)
    
    fn add_known_fact(mut self, fact: MangleFact):
        """Add a known fact for invariant checking."""
        self.safety_validator.add_known_fact(fact)
    
    fn validate_fact(
        mut self,
        fact: MangleFact,
        confidence: Float32 = 1.0
    ) -> ValidationResult:
        """
        Validate a single fact.
        
        Args:
            fact: The fact to validate
            confidence: LLM confidence score (0-1)
        
        Returns:
            ValidationResult with validity status and any error details
        """
        var start_time = now()
        
        # Step 1: Schema validation
        var schema_result = self.schema_validator.validate(fact, confidence)
        if not schema_result.is_valid:
            self.facts_rejected += 1
            schema_result.validation_time_ns = now() - start_time
            self.total_validation_time_ns += schema_result.validation_time_ns
            return schema_result
        
        # Step 2: Safety invariant validation
        var safety_result = self.safety_validator.validate(fact)
        if not safety_result.is_valid:
            self.facts_rejected += 1
            safety_result.validation_time_ns = now() - start_time
            self.total_validation_time_ns += safety_result.validation_time_ns
            return safety_result
        
        # Fact is valid
        self.facts_validated += 1
        var result = ValidationResult(fact)
        result.set_valid(confidence)
        result.validation_time_ns = now() - start_time
        self.total_validation_time_ns += result.validation_time_ns
        return result
    
    fn validate_llm_output(
        mut self,
        llm_output: String,
        base_confidence: Float32 = 0.8
    ) -> BatchValidationResult:
        """
        Parse and validate all facts from LLM output.
        
        Args:
            llm_output: Raw LLM output containing Mangle facts
            base_confidence: Default confidence for facts without explicit score
        
        Returns:
            BatchValidationResult with all validation results
        """
        var batch_result = BatchValidationResult()
        var start_time = now()
        
        # Parse LLM output into facts
        var parser = MangleParser()
        parser.parse_file_content(llm_output)
        
        # Validate each fact
        for i in range(len(parser.facts)):
            var fact = parser.facts[i]
            
            # Extract confidence if embedded in fact (e.g., last arg is confidence)
            var confidence = base_confidence
            if fact.num_args > 0:
                var last_arg = fact.get_arg(fact.num_args - 1)
                try:
                    var parsed_conf = float(last_arg)
                    if parsed_conf >= 0.0 and parsed_conf <= 1.0:
                        confidence = Float32(parsed_conf)
                except:
                    pass
            
            var result = self.validate_fact(fact, confidence)
            batch_result.add_result(result)
        
        batch_result.total_time_ns = now() - start_time
        return batch_result
    
    fn get_valid_facts(self, batch_result: BatchValidationResult) -> List[MangleFact]:
        """Extract only valid facts from a batch result."""
        var valid_facts = List[MangleFact]()
        for i in range(len(batch_result.results)):
            if batch_result.results[i].is_valid:
                valid_facts.append(batch_result.results[i].fact)
        return valid_facts
    
    fn get_statistics(self) -> String:
        """Get validation statistics as a report string."""
        var total = self.facts_validated + self.facts_rejected
        var acceptance_rate = Float32(0.0)
        if total > 0:
            acceptance_rate = Float32(self.facts_validated) / Float32(total) * 100.0
        
        var avg_time_us = Float32(0.0)
        if total > 0:
            avg_time_us = Float32(self.total_validation_time_ns) / Float32(total) / 1000.0
        
        return (
            "LLM Fact Validation Statistics:\n" +
            "  Total facts processed: " + String(total) + "\n" +
            "  Facts validated: " + String(self.facts_validated) + "\n" +
            "  Facts rejected: " + String(self.facts_rejected) + "\n" +
            "  Acceptance rate: " + String(acceptance_rate) + "%\n" +
            "  Avg validation time: " + String(avg_time_us) + " μs\n"
        )
    
    fn emit_audit_facts(self, batch_result: BatchValidationResult) -> List[String]:
        """
        Generate Mangle audit facts for the validation batch.
        These can be asserted back into the knowledge base for governance tracking.
        """
        var audit_facts = List[String]()
        var timestamp = now()
        
        # Summary fact
        audit_facts.append(
            "validation_batch(" +
            String(timestamp) + ", " +
            String(batch_result.total_count) + ", " +
            String(batch_result.valid_count) + ", " +
            String(batch_result.invalid_count) + ")."
        )
        
        # Individual rejection facts for audit trail
        for i in range(len(batch_result.results)):
            var result = batch_result.results[i]
            if not result.is_valid:
                audit_facts.append(
                    "validation_rejected(\"" + result.fact.predicate + "\", \"" +
                    result.error_code + "\", \"" + result.error_message + "\", " +
                    String(timestamp) + ")."
                )
        
        return audit_facts


# =============================================================================
# CONVENIENCE FUNCTIONS
# =============================================================================

fn create_default_gateway() -> LLMFactValidationGateway:
    """Create a gateway with default safety schemas registered."""
    return LLMFactValidationGateway()


fn validate_single_fact(
    predicate: String,
    args: List[String],
    confidence: Float32 = 0.8
) -> ValidationResult:
    """
    Convenience function to validate a single fact.
    
    Example:
        var args = List[String]("req123", "toxic", "low", "0.95")
        var result = validate_single_fact("safety_assessment", args, 0.95)
    """
    var gateway = create_default_gateway()
    var fact = MangleFact(predicate)
    for i in range(len(args)):
        fact.add_arg(args[i])
    return gateway.validate_fact(fact, confidence)