apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: privatellm-inference-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      serving.kserve.io/inferenceservice: privatellm-inference
