"""
Mangle Query Service - OpenAI-compatible HTTP API.

Provides OpenAI-compatible endpoints with Mangle routing rules.

Modules:
- router: FastAPI application and routing
- models: Request/response data models for chat completions
- chat_completions: Chat completion handler
- embeddings: Embeddings endpoint handler
- models_endpoint: Models listing and retrieval endpoint
- sse_streaming: Server-Sent Events streaming utilities
"""

from .router import app

# Request/Response models
from .models import (
    ChatCompletionRequest,
    ChatCompletionResponse,
    ChatMessage,
    Role,
    FinishReason,
    ErrorResponse,
)

# Endpoint handlers
from .chat_completions import ChatCompletionsHandler
from .embeddings import EmbeddingsHandler
from .models_endpoint import (
    ModelsHandler,
    ModelObject,
    ModelObjectExtended,
    ModelsListResponse,
    ModelsListResponseExtended,
    DeleteModelResponse,
    ModelErrorResponse,
    get_models_handler,
    list_all_models,
    get_model_info,
    model_supports_streaming,
    model_supports_tools,
    get_recommended_model,
)

from .completions import (
    CompletionRequest,
    CompletionResponse,
    CompletionChoice,
    CompletionUsage,
    CompletionLogprobs,
    CompletionChunk,
    CompletionStreamChoice,
    CompletionErrorResponse,
    CompletionsHandler,
    get_completions_handler,
    create_completion,
    estimate_token_count,
    estimate_prompt_tokens,
)

from .audio import (
    AudioResponseFormat,
    TimestampGranularity,
    TranscriptionRequest,
    TranscriptionResponse,
    TranscriptionWord,
    TranscriptionSegment,
    TranslationRequest,
    TranslationResponse,
    AudioErrorResponse,
    AudioHandler,
    get_audio_handler,
    transcribe_audio,
    translate_audio,
    validate_audio_file,
    SUPPORTED_AUDIO_FORMATS,
)

from .files import (
    FilePurpose,
    FileStatus,
    FileObject,
    FileListResponse,
    FileDeleteResponse,
    FileContentResponse,
    FileErrorResponse,
    FilesHandler,
    get_files_handler,
    upload_file,
    list_files,
    get_file,
    delete_file,
    validate_file,
    validate_jsonl_content,
    SUPPORTED_PURPOSES,
)

from .images import (
    ImageSize,
    ImageResponseFormat,
    ImageStyle,
    ImageQuality,
    ImageGenerationRequest,
    ImageEditRequest,
    ImageVariationRequest,
    ImageData,
    ImagesResponse,
    ImageErrorResponse,
    ImagesHandler,
    get_images_handler,
    generate_image,
    edit_image,
    create_image_variation,
    validate_image_file,
    SUPPORTED_IMAGE_FORMATS,
)

from .moderations import (
    ModerationModel,
    ModerationCategory,
    ModerationRequest,
    CategoryScores,
    CategoryFlags,
    ModerationResult,
    ModerationResponse,
    ModerationErrorResponse,
    ModerationsHandler,
    get_moderations_handler,
    moderate_text,
    is_content_safe,
    get_flagged_categories,
    validate_moderation_input,
    SUPPORTED_MODERATION_MODELS,
    DEFAULT_THRESHOLD,
    TEXT_MODERATION_CATEGORIES,
    OMNI_MODERATION_CATEGORIES,
)

from .fine_tuning import (
    FineTuningStatus,
    FineTuningEventLevel,
    FineTuningEventType,
    Hyperparameters,
    WandbIntegration,
    FineTuningJobRequest,
    ListJobsRequest,
    ListEventsRequest,
    FineTuningError,
    FineTuningJobObject,
    FineTuningEvent,
    FineTuningCheckpoint,
    FineTuningJobListResponse,
    FineTuningEventListResponse,
    FineTuningCheckpointListResponse,
    FineTuningErrorResponse,
    FineTuningHandler,
    get_fine_tuning_handler,
    create_fine_tuning_job,
    validate_training_file_id,
    is_finetune_model,
    get_base_model,
    FINETUNE_BASE_MODELS,
)

from .fine_tuning_advanced import (
    ValidationErrorCode,
    ValidationError,
    ValidationResult,
    TrainingDataValidator,
    TrainingMetrics,
    MetricsTracker,
    TrainingSimulator,
    FineTunedModelNamer,
    AdvancedFineTuningHandler,
    get_advanced_fine_tuning_handler,
    validate_training_data,
    estimate_training_cost,
    generate_sample_training_data,
)

from .batches import (
    BatchStatus,
    BatchEndpoint,
    BatchRequest,
    BatchRequestCounts,
    BatchErrors,
    BatchObject,
    BatchListResponse,
    BatchInputLine,
    BatchOutputLine,
    BatchErrorResponse,
    BatchesHandler,
    get_batches_handler,
    create_batch,
    generate_batch_input,
    parse_batch_output,
    validate_batch_request,
    is_batch_complete,
    get_batch_progress,
    SUPPORTED_ENDPOINTS,
    BATCH_COMPLETION_WINDOWS,
    MAX_REQUESTS_PER_BATCH,
)

from .assistants import (
    ASSISTANT_MODELS,
    DEFAULT_MODEL,
    MAX_TOOLS_PER_ASSISTANT,
    ToolType,
    ResponseFormat,
    TruncationStrategy,
    CodeInterpreterTool,
    FileSearchTool,
    FunctionDefinition,
    FunctionTool,
    ToolResources,
    CreateAssistantRequest,
    ModifyAssistantRequest,
    AssistantObject,
    AssistantListResponse,
    AssistantDeleteResponse,
    AssistantErrorResponse,
    AssistantsHandler,
    get_assistants_handler,
    create_assistant,
    create_code_interpreter_tool,
    create_file_search_tool,
    create_function_tool,
    validate_assistant_request,
    is_valid_tool_type,
    get_supported_models,
)

from .threads import (
    MAX_THREAD_METADATA_PAIRS,
    MAX_MESSAGE_CONTENT_LENGTH,
    MAX_MESSAGES_PER_THREAD,
    MessageRole,
    MessageContentType,
    MessageStatus,
    TextContent,
    ImageFileContent,
    ImageUrlContent,
    Attachment,
    CreateThreadRequest,
    ModifyThreadRequest,
    ThreadObject,
    ThreadDeleteResponse,
    CreateMessageRequest,
    ModifyMessageRequest,
    MessageObject,
    MessageListResponse,
    MessageDeleteResponse,
    ThreadsErrorResponse,
    ThreadsHandler,
    get_threads_handler,
    create_thread,
    create_message,
    create_text_content,
    create_image_file_content,
    create_image_url_content,
    create_attachment,
    extract_text_from_message,
    is_user_message,
    is_assistant_message,
)

from .runs import (
    MAX_INSTRUCTIONS_LENGTH,
    MAX_ADDITIONAL_INSTRUCTIONS_LENGTH,
    MAX_TOOL_OUTPUTS_PER_SUBMIT,
    RUN_TIMEOUT_DEFAULT,
    RunStatus,
    RunStepType,
    RunStepStatus,
    RequiredActionType,
    IncompleteReason,
    ToolOutput,
    ToolCall,
    RequiredAction,
    LastError,
    IncompleteDetails,
    RunUsage,
    TruncationStrategy,
    CreateRunRequest,
    ModifyRunRequest,
    SubmitToolOutputsRequest,
    RunObject,
    RunListResponse,
    RunErrorResponse,
    RunsHandler,
    get_runs_handler,
    create_run,
    is_run_terminal,
    is_run_active,
    can_cancel_run,
    requires_tool_outputs,
    get_required_tool_calls,
    create_tool_output,
    estimate_run_cost,
)

from .run_steps import (
    MAX_STREAM_BUFFER_SIZE,
    STREAM_KEEPALIVE_INTERVAL,
    RunStepType as RunStepTypeEnum,
    RunStepStatus as RunStepStatusEnum,
    ToolCallType,
    StreamEventType,
    MessageCreationStepDetails,
    CodeInterpreterOutput,
    CodeInterpreterToolCall,
    FileSearchToolCall,
    FunctionToolCall,
    ToolCallsStepDetails,
    RunStepObject,
    RunStepListResponse,
    RunStepDelta,
    CreateThreadAndRunRequest,
    StreamEvent,
    RunStepErrorResponse,
    RunStepsHandler,
    RunStreamHandler,
    AdvancedRunsHandler,
    get_run_steps_handler,
    get_advanced_runs_handler,
    create_message_step_details,
    create_tool_calls_step_details,
    create_code_interpreter_tool_call,
    create_file_search_tool_call,
    create_function_tool_call,
    is_step_terminal,
    parse_stream_events,
)

__all__ = [
    # Application
    "app",
    # Models
    "ChatCompletionRequest",
    "ChatCompletionResponse",
    "ChatMessage",
    "Role",
    "FinishReason",
    "ErrorResponse",
    # Handlers
    "ChatCompletionsHandler",
    "EmbeddingsHandler",
    "ModelsHandler",
    "ModelObject",
    "ModelsListResponse",
    # Utilities
    "get_models_handler",
    "list_all_models",
    "get_model_info",
    "SSEFormatter",
    "format_sse_event",
    "format_sse_done",
]