#!/usr/bin/env python3
"""
add_spdx_headers.py — Prepend SPDX-License-Identifier + SPDX-FileCopyrightText to
every source file in SAP-owned services that does not already have them.

Rules:
  - Idempotent: files already carrying SPDX headers are untouched.
  - Shebang-aware: #!/usr/bin/env ... line stays as line 1.
  - Skips generated files (DO NOT EDIT, Code generated, AUTO-GENERATED).
  - Skips vendor / node_modules / dist / build / target / .venv directories.
  - Does NOT touch: mangle-main (Google LLC copyright already present →
    covered by REUSE.toml), vllm-main, elasticsearch-main (upstream OSS),
    ai-core-pal / ai-core-streaming (empty stubs).

Exit codes:
  0 — success
  1 — at least one file could not be updated

Usage:
  # Preview changes without writing anything
  python3 scripts/sbom-lineage/add_spdx_headers.py --dry-run

  # Apply to all services
  python3 scripts/sbom-lineage/add_spdx_headers.py

  # Apply to a single service
  python3 scripts/sbom-lineage/add_spdx_headers.py --service cap-llm-plugin-main
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]

# ── Service metadata ──────────────────────────────────────────────────────────
# (path relative to repo root) → {license, copyright, year, extensions}
SERVICE_METADATA: dict[str, dict] = {
    "training-console": {
        "license":   "Apache-2.0",
        "copyright": "SAP SE",
        "year":      "2024",
        "exts":      {".py", ".sh"},
    },
    "langchain-integration-for-sap-hana-cloud-main": {
        "license":   "Apache-2.0",
        "copyright": "SAP SE",
        "year":      "2023",
        "exts":      {".py"},
    },
    "generative-ai-toolkit-for-sap-hana-cloud-main": {
        "license":   "Apache-2.0",
        "copyright": "SAP SE",
        "year":      "2024",
        "exts":      {".py"},
    },
    "cap-llm-plugin-main": {
        "license":   "Apache-2.0",
        "copyright": "SAP SE",
        "year":      "2023",
        "exts":      {".ts", ".js", ".mjs", ".cjs"},
    },
    "odata-vocabularies-main": {
        "license":   "Apache-2.0",
        "copyright": "SAP SE",
        "year":      "2019",
        "exts":      {".js", ".ts", ".sh"},
    },
    "ai-sdk-js-main": {
        "license":   "Apache-2.0",
        "copyright": "SAP SE",
        "year":      "2024",
        "exts":      {".ts", ".js", ".mjs"},
    },
    "ui5-webcomponents-ngx-main": {
        "license":   "Apache-2.0",
        "copyright": "SAP SE",
        "year":      "2023",
        "exts":      {".ts", ".js"},
    },
    "world-monitor-main": {
        "license":   "AGPL-3.0-only",
        "copyright": "Elie Habib",
        "year":      "2024",
        "exts":      {".rs"},
    },
    "mangle-query-service": {
        "license":   "Apache-2.0",
        "copyright": "SAP SE",
        "year":      "2024",
        "exts":      {".go"},
    },
}

# Directories always skipped
_SKIP_DIRS = {
    "node_modules", ".git", "__pycache__", "dist", "build", "target",
    "vendor", ".venv", "venv", ".sbom-venv", ".tox", "coverage",
    ".nyc_output", "generated", "gen", ".cargo",
}

# Patterns that mark auto-generated files (check first 6 lines)
_GENERATED_RE = re.compile(
    r"(DO NOT EDIT|Code generated|AUTO-GENERATED|@generated|autogenerated)",
    re.IGNORECASE,
)

_SPDX_PRESENT_RE = re.compile(r"SPDX-License-Identifier", re.IGNORECASE)
_SHEBANG_RE      = re.compile(r"^#!")


def _comment_prefix(ext: str) -> str:
    if ext in (".py", ".sh", ".bash", ".zsh", ".yaml", ".yml"):
        return "#"
    return "//"


def _make_header(license_id: str, copyright: str, year: str, ext: str) -> str:
    prefix = _comment_prefix(ext)
    return (
        f"{prefix} SPDX-License-Identifier: {license_id}\n"
        f"{prefix} SPDX-FileCopyrightText: {year} {copyright}\n"
    )


def _is_generated(text: str) -> bool:
    head = "\n".join(text.splitlines()[:6])
    return bool(_GENERATED_RE.search(head))


def process_file(
    path: Path,
    meta: dict,
    *,
    dry_run: bool,
) -> str:
    """
    Add SPDX header to *path* if not already present.
    Returns one of: 'added', 'exists', 'generated', 'skipped', 'error'.
    """
    try:
        raw = path.read_bytes()
    except OSError:
        return "error"

    # Skip binary files
    try:
        text = raw.decode("utf-8")
    except UnicodeDecodeError:
        return "skipped"

    if _SPDX_PRESENT_RE.search(text[:512]):
        return "exists"
    if _is_generated(text):
        return "generated"

    header = _make_header(meta["license"], meta["copyright"], meta["year"], path.suffix)
    lines  = text.splitlines(keepends=True)

    # Keep shebang as first line
    if lines and _SHEBANG_RE.match(lines[0]):
        new_content = lines[0] + header + "".join(lines[1:])
    else:
        new_content = header + text

    if not dry_run:
        path.write_text(new_content, encoding="utf-8")
    return "added"


def process_service(
    service_path: str,
    meta: dict,
    *,
    dry_run: bool,
    verbose: bool,
) -> dict[str, int]:
    svc_dir = REPO_ROOT / service_path
    if not svc_dir.is_dir():
        print(f"  [WARN] Directory not found: {svc_dir}", file=sys.stderr)
        return {}

    counts: dict[str, int] = {"added": 0, "exists": 0, "generated": 0, "skipped": 0, "error": 0}

    for fpath in svc_dir.rglob("*"):
        if not fpath.is_file():
            continue
        if any(part in _SKIP_DIRS for part in fpath.parts):
            continue
        if fpath.suffix.lower() not in meta["exts"]:
            continue

        result = process_file(fpath, meta, dry_run=dry_run)
        counts[result] = counts.get(result, 0) + 1

        if verbose and result == "added":
            rel = fpath.relative_to(REPO_ROOT)
            tag = "[DRY-RUN] " if dry_run else ""
            print(f"    {tag}+ {rel}")

    return counts


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Add SPDX-License-Identifier headers to SAP-owned source files"
    )
    parser.add_argument("--dry-run",  action="store_true",
                        help="Preview changes without writing any files")
    parser.add_argument("--service",  default=None,
                        help="Process only this service (directory name)")
    parser.add_argument("--verbose",  action="store_true",
                        help="Print each added file")
    args = parser.parse_args()

    if args.service and args.service not in SERVICE_METADATA:
        print(f"Unknown service: {args.service}", file=sys.stderr)
        print(f"Known services: {', '.join(SERVICE_METADATA)}", file=sys.stderr)
        sys.exit(1)

    services = (
        {args.service: SERVICE_METADATA[args.service]}
        if args.service
        else SERVICE_METADATA
    )

    tag = "[DRY-RUN] " if args.dry_run else ""
    print(f"\n{'='*72}")
    print(f"  {tag}SPDX HEADER INJECTION")
    print("=" * 72)

    grand: dict[str, int] = {}
    errors = False
    for svc_path, meta in services.items():
        print(f"\n  {svc_path}  [{meta['license']} © {meta['year']} {meta['copyright']}]")
        counts = process_service(svc_path, meta, dry_run=args.dry_run, verbose=args.verbose)
        for k, v in counts.items():
            grand[k] = grand.get(k, 0) + v
        added     = counts.get("added", 0)
        exists    = counts.get("exists", 0)
        generated = counts.get("generated", 0)
        skipped   = counts.get("skipped", 0)
        err       = counts.get("error", 0)
        print(f"    {tag}added={added}  already_ok={exists}  generated={generated}  "
              f"binary={skipped}  errors={err}")
        if err:
            errors = True

    print(f"\n{'='*72}")
    print(f"  TOTALS  added={grand.get('added',0)}  already_ok={grand.get('exists',0)}  "
          f"generated={grand.get('generated',0)}  errors={grand.get('error',0)}")
    if args.dry_run:
        print("  (dry-run — no files written)")
    print("=" * 72)

    if errors:
        sys.exit(1)


if __name__ == "__main__":
    main()

